set dotenv-load := true
set shell := ["bash", "-c"]

default:
    @just --list

import "just/docker.justfile"
import "just/db.justfile"
import "just/qa.justfile"
import "just/docs.justfile"

# Clean up temp files
clean:
    find . -type d -name "__pycache__" -exec rm -rf {} +
    find . -type d -name ".pytest_cache" -exec rm -rf {} +
