"""init gold standard schema

Revision ID: 963e02ce0b17
Revises: 
Create Date: 2026-09-16 14:54:41.911827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '963e02ce0b17'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arxiv_documents',
    sa.Column('arxiv_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('markdown_content', sa.Text(), nullable=False),
    sa.Column('authors', postgresql.ARRAY(sa.String()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('categories', postgresql.ARRAY(sa.String()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('pdf_url', sa.String(), nullable=False),
    sa.Column('published_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('embedding_status', sa.String(length=20), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('public_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_arxiv_documents'))
    )
    op.create_index(op.f('ix_arxiv_documents_arxiv_id'), 'arxiv_documents', ['arxiv_id'], unique=True)
    op.create_index(op.f('ix_arxiv_documents_embedding_status'), 'arxiv_documents', ['embedding_status'], unique=False)
    op.create_index(op.f('ix_arxiv_documents_public_id'), 'arxiv_documents', ['public_id'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('public_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("email ~ '^[^@]+@[^@]+\\.[^@]+$'", name=op.f('ck_users_email_format')),
    sa.CheckConstraint('LENGTH(hashed_password) > 0', name=op.f('ck_users_password_not_empty')),
    sa.CheckConstraint('created_at <= updated_at', name=op.f('ck_users_timestamps_ordered')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_public_id'), 'users', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_public_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_arxiv_documents_public_id'), table_name='arxiv_documents')
    op.drop_index(op.f('ix_arxiv_documents_embedding_status'), table_name='arxiv_documents')
    op.drop_index(op.f('ix_arxiv_documents_arxiv_id'), table_name='arxiv_documents')
    op.drop_table('arxiv_documents')
    # ### end Alembic commands ###
