name: Backend CI

on:
  push:
    branches: ["main"]
    paths:
      - "backend/**" # Only trigger if files in the backend folder change
  pull_request:
    branches: ["main"]
    paths:
      - "backend/**"

jobs:
  code-quality:
    name: Lint & Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend # Set execution path for all steps in this job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "backend/pyproject.toml" # Update path here too

      - name: Install dependencies
        run: uv sync --frozen

      - name: Run Ruff (Lint Check)
        run: uv run ruff check .

      - name: Run Pytest
        run: uv run pytest -v

  docker-checks:
    name: Docker Lint & Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint Dockerfiles (Hadolint)
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: backend/docker/Dockerfile

      - name: Lint Dev Dockerfile (Hadolint)
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: backend/docker/Dockerfile.dev

      - name: Build Production Image
        run: docker build -f docker/Dockerfile -t backend-app:test .
